# Generated by Django 5.2.7 on 2025-11-14 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamparticipationmatch',
            options={'ordering': ['-is_home']},
        ),
        migrations.AlterUniqueTogether(
            name='teamparticipationmatch',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='teamparticipationmatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='matches.match', verbose_name='Match in which the team is participating'),
        ),
        migrations.AlterField(
            model_name='teamparticipationmatch',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_participations', to='matches.team', verbose_name='Team participating in the match'),
        ),
        migrations.AddConstraint(
            model_name='teamparticipationmatch',
            constraint=models.UniqueConstraint(fields=('team', 'match'), name='unique_team_match_participation'),
        ),
        migrations.AddConstraint(
            model_name='teamparticipationmatch',
            constraint=models.UniqueConstraint(fields=('match', 'is_home'), name='unique_home_team_per_match'),
        ),
    ]
