# Generated by Django 5.2.7 on 2025-11-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_teamparticipationmatch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=40, unique=True, verbose_name='Unique slug'),
        ),
    ]
