# Generated by Django 5.2.7 on 2026-02-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_team_name_alter_team_short_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Role in the league')),
                ('instagram', models.CharField(blank=True, max_length=50, verbose_name='Instagram handle')),
                ('isLeader', models.BooleanField(default=False, verbose_name='Is this staff member a league leader?')),
                ('local_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='matches.localleague', verbose_name='Local league to which the staff member belongs')),
            ],
        ),
    ]
