# Generated by Django 5.2.7 on 2026-02-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(default='Coordinatore staff', max_length=50, verbose_name='Role in the league'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Partner name')),
                ('logo', models.ImageField(upload_to='partner_logos/', verbose_name='Partner logo')),
                ('url', models.URLField(blank=True, verbose_name='Partner website')),
                ('local_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='matches.localleague', verbose_name='Local league to which the partner belongs')),
            ],
        ),
    ]
