# Generated by Django 5.2.7 on 2026-02-19 15:40

import backend_django.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_staff_role_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='localleague',
            name='socials',
            field=models.JSONField(blank=True, default=dict, verbose_name='Social media handles'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(storage=backend_django.storage_backends.PublicMediaStorage, upload_to='partner_logos/', verbose_name='Partner logo'),
        ),
    ]
