# Generated by Django 5.2.7 on 2026-02-19 16:10

import backend_django.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_localleague_socials_alter_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.CharField(blank=True, max_length=50, verbose_name='Coach name'),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=backend_django.storage_backends.PublicMediaStorage, upload_to='team_logos/', verbose_name='Team logo'),
        ),
    ]
