# Generated by Django 5.2.7 on 2026-02-19 21:37

import backend_django.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_team_coach_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='localleague',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=backend_django.storage_backends.PublicMediaStorage, upload_to='league_logos/', verbose_name='League logo'),
        ),
    ]
