# Generated by Django 5.2.7 on 2026-02-19 22:07

import backend_django.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_localleague_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='localleague',
            name='background',
            field=models.ImageField(blank=True, null=True, storage=backend_django.storage_backends.PublicMediaStorage, upload_to='league_backgrounds/', verbose_name='League page background'),
        ),
    ]
