# Generated by Django 5.2.7 on 2026-02-26 14:06

import backend_django.storage_backends
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_localleague_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Unique slug')),
                ('title', models.CharField(max_length=200, verbose_name='News title')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='News subtitle')),
                ('content', models.TextField(verbose_name='News content')),
                ('date', models.DateField(verbose_name='Publication date')),
                ('image', models.ImageField(blank=True, null=True, storage=backend_django.storage_backends.PublicMediaStorage, upload_to='news_images/', verbose_name='News image')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Author name')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Comma-separated tags')),
                ('local_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='matches.localleague', verbose_name='Local league to which the news belongs')),
            ],
        ),
    ]
