# Generated by Django 5.2.7 on 2026-02-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='finished',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FT', 'Finished')], default='SCHEDULED', help_text='Current status of the match', max_length=10, verbose_name='Match status'),
        ),
    ]
