# Generated by Django 5.2.7 on 2026-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_remove_match_finished_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('Gironi', 'Group stage'), ('Quarti', 'Quarter-finals'), ('Semi', 'Semi-finals'), ('Finale', 'Final')], default='GROUP', help_text='Select the tournament stage for this match', max_length=10, verbose_name='Tournament stage'),
        ),
    ]
