# Generated by Django 5.2.7 on 2026-02-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_match_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('Ammichevole', 'Friendly'), ('Gironi', 'Group stage'), ('Quarti', 'Quarter-finals'), ('Semi', 'Semi-finals'), ('Finale', 'Final'), ('Finali nazionali', 'National finals')], default='Gironi', help_text='Select the tournament stage for this match', max_length=32, verbose_name='Tournament stage'),
        ),
    ]
