# Generated by Django 5.2.7 on 2026-04-15 14:22

import backend_django.storage_backends
import matches.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_alter_match_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=matches.custom_fields.SVGAndImageField(storage=backend_django.storage_backends.PublicMediaStorage, upload_to='partner_logos/', verbose_name='Partner logo'),
        ),
    ]
