# Generated by Django 5.2.7 on 2026-04-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_alter_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('Ammichevole', 'Friendly'), ('Gironi', 'Group stage'), ('Ottavi', 'round-of-16'), ('Quarti', 'Quarter-finals'), ('Semi', 'Semi-finals'), ('Finale', 'Final'), ('Finali nazionali', 'National finals')], default='Gironi', help_text='Select the tournament stage for this match', max_length=32, verbose_name='Tournament stage'),
        ),
    ]
