# Generated by Django 5.2.7 on 2025-11-14 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('code_fiscal', models.CharField(max_length=16, verbose_name='Fiscal Code')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('code_fiscal', models.CharField(max_length=16, unique=True, verbose_name='Fiscal Code')),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99, message='Shirt number cannot exceed 99'), django.core.validators.MinValueValidator(1, message='Shirt number must be at least 1')], verbose_name='Shirt number')),
                ('shirt_size', models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=5, null=True, verbose_name='Shirt size')),
                ('position', models.CharField(blank=True, choices=[('POR', 'Portiere'), ('DIF', 'Difensore'), ('CEN', 'Centrocampista'), ('ATT', 'Attaccante')], max_length=5, null=True, verbose_name='Playing position')),
                ('parent', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_parent', to='player_registration.parent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='player_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
