# Generated by Django 5.2.7 on 2025-11-14 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_teamparticipationmatch_options_and_more'),
        ('player_registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Team Name')),
                ('registration_token', models.CharField(max_length=100, unique=True, verbose_name='Registration token')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='player_list_manager', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_player_lists', to='matches.team', verbose_name='Team to which the player list belongs')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_list',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='player_registration.playerlist', verbose_name='Player list to which the player belongs'),
        ),
    ]
