# Generated by Django 5.2.7 on 2025-11-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0003_alter_player_first_name_alter_player_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='code_fiscal',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Fiscal Code'),
        ),
    ]
