# Generated by Django 5.2.7 on 2025-11-15 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0004_alter_player_code_fiscal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='parent',
        ),
        migrations.AddField(
            model_name='parent',
            name='player',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='player_registration.player', verbose_name='Player associated with this parent'),
            preserve_default=False,
        ),
    ]
