# Generated by Django 5.2.7 on 2025-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0005_remove_player_parent_parent_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Privacy policy accepted at'),
        ),
        migrations.AddField(
            model_name='player',
            name='registration_status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('EDIT', 'Editable'), ('SUB', 'Submitted')], default='PEND', max_length=6, verbose_name='Registration status'),
        ),
    ]
