# Generated by Django 5.2.7 on 2025-11-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0006_player_privacy_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerlist',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Registration fee'),
        ),
        migrations.AddField(
            model_name='playerlist',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Submitted at'),
        ),
    ]
