# Generated by Django 5.2.7 on 2025-11-24 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0008_deletionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletionrequest',
            name='user_to_be_deleted',
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='player_to_be_deleted',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='player_registration.player'),
            preserve_default=False,
        ),
    ]
