# Generated by Django 5.2.7 on 2025-11-24 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0009_remove_deletionrequest_user_to_be_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionrequest',
            name='player_to_be_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to='player_registration.player'),
        ),
    ]
