# Generated by Django 5.2.7 on 2025-11-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0010_alter_deletionrequest_player_to_be_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionrequest',
            name='deletion_info',
            field=models.TextField(blank=True, null=True, verbose_name='Information about deletion request'),
        ),
    ]
