# Generated by Django 5.2.7 on 2025-11-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0012_alter_deletionrequest_deletion_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(max_length=32, unique=True, verbose_name='Reset token'),
        ),
    ]
