# Generated by Django 5.2.7 on 2025-11-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0013_alter_passwordresetrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(max_length=64, unique=True, verbose_name='Reset token'),
        ),
    ]
