# Generated by Django 5.2.7 on 2025-11-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0015_player_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Place of birth'),
        ),
        migrations.AddField(
            model_name='player',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Place of birth'),
        ),
    ]
