# Generated by Django 5.2.7 on 2025-11-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0016_parent_place_of_birth_player_place_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(max_length=128, verbose_name='Reset token'),
        ),
        migrations.AlterField(
            model_name='usermailverification',
            name='token',
            field=models.CharField(max_length=128, verbose_name='Verification token'),
        ),
    ]
