# Generated by Django 5.2.7 on 2025-11-26 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_teamparticipationmatch_options_and_more'),
        ('player_registration', '0017_alter_passwordresetrequest_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed at')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('processing_errors', models.TextField(blank=True, null=True, verbose_name='Processing errors')),
                ('file', models.FileField(upload_to='registration_player_lists/', verbose_name='Upload file')),
                ('local_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='matches.localleague')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
