# Generated by Django 5.2.7 on 2025-11-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0018_bulkuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploads',
            name='manager_email_column',
            field=models.CharField(default='Mail referente squadra', max_length=50, verbose_name='Manager email column'),
        ),
        migrations.AddField(
            model_name='bulkuploads',
            name='separator',
            field=models.CharField(default=';', max_length=5, verbose_name='CSV Separator'),
        ),
        migrations.AddField(
            model_name='bulkuploads',
            name='team_name_column',
            field=models.CharField(default='Squadra (nome completo)', max_length=50, verbose_name='Team name column'),
        ),
        migrations.AddField(
            model_name='bulkuploads',
            name='team_name_short_column',
            field=models.CharField(default='Squadra (abbreviazione 3 lettere)', max_length=50, verbose_name='Team short name column'),
        ),
        migrations.AlterField(
            model_name='bulkuploads',
            name='file',
            field=models.FileField(upload_to='bulk_upload_player_lists/', verbose_name='Upload file'),
        ),
    ]
