# Generated by Django 5.2.7 on 2025-11-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0019_bulkuploads_manager_email_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploads',
            name='processing_errors',
            field=models.TextField(blank=True, default='', verbose_name='Processing errors'),
        ),
    ]
