# Generated by Django 5.2.7 on 2025-11-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0020_alter_bulkuploads_processing_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploads',
            name='processed_wo_errors',
            field=models.BooleanField(null=True, verbose_name='Processed with errors'),
        ),
    ]
