# Generated by Django 5.2.7 on 2025-11-26 20:52

import backend_django.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0021_bulkuploads_processed_wo_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploads',
            name='file',
            field=models.FileField(storage=backend_django.storage_backends.PrivateMediaStorage(), upload_to='bulk_upload_player_lists/', verbose_name='Upload file'),
        ),
        migrations.AlterField(
            model_name='bulkuploads',
            name='processed_wo_errors',
            field=models.BooleanField(null=True, verbose_name='Processed without errors'),
        ),
    ]
