# Generated by Django 5.2.7 on 2025-12-08 16:35

import backend_django.storage_backends
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0022_alter_bulkuploads_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('confirmed_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Confirmed at')),
                ('expires_at', models.DateField(verbose_name='Expires at')),
                ('file', models.FileField(storage=backend_django.storage_backends.PrivateMediaStorage(), upload_to='medical_certificates/', verbose_name='Medical certificate file')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificates', to='player_registration.player')),
            ],
        ),
    ]
