# Generated by Django 5.2.7 on 2025-12-21 15:25

import backend_django.storage_backends
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0023_medicalcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='file',
            field=models.FileField(storage=backend_django.storage_backends.PrivateMediaStorage(), upload_to='medical_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Medical certificate file'),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificate', to='player_registration.player'),
        ),
    ]
