# Generated by Django 5.2.7 on 2025-12-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0024_alter_medicalcertificate_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcertificate',
            name='confirmed_at',
        ),
    ]
