# Generated by Django 5.2.7 on 2025-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0025_remove_medicalcertificate_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcertificate',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted at'),
        ),
    ]
