# Generated by Django 5.2.7 on 2025-12-21 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0026_medicalcertificate_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='player',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificate', to='player_registration.player'),
        ),
    ]
