# Generated by Django 5.2.7 on 2025-12-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0027_alter_medicalcertificate_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcertificate',
            name='id',
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medical_certificate', serialize=False, to='player_registration.player'),
        ),
    ]
