# Generated by Django 5.2.7 on 2025-12-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0028_remove_medicalcertificate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='expires_at',
            field=models.DateField(null=True, verbose_name='Expires at'),
        ),
    ]
