# Generated by Django 5.2.7 on 2025-12-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0029_alter_medicalcertificate_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploads',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Price'),
        ),
    ]
