# Generated by Django 5.2.7 on 2025-12-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0030_bulkuploads_registration_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128, unique=True, verbose_name='Stripe session ID')),
                ('amount_total', models.IntegerField(verbose_name='Amount total (in cents)')),
                ('currency', models.CharField(max_length=10, verbose_name='Currency')),
                ('payer_email', models.EmailField(max_length=254, verbose_name='Payer email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('scope', models.CharField(choices=[('PLAYER_REGISTRATION_FEE', 'Player Registration Fee')], max_length=50, verbose_name='Payment scope')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='payment_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_subscriptions', to='player_registration.paymenttransaction'),
        ),
    ]
