# Generated by Django 5.2.7 on 2025-12-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0031_paymenttransaction_player_payment_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='payment_object',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error message'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified at'),
        ),
        migrations.AddField(
            model_name='player',
            name='payment_transactions',
            field=models.ManyToManyField(blank=True, related_name='player_subscriptions', to='player_registration.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount total (in cents)'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Payer email'),
        ),
    ]
