# Generated by Django 5.2.7 on 2025-12-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0032_remove_player_payment_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Error message'),
        ),
    ]
