# Generated by Django 5.2.7 on 2026-04-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_registration', '0033_alter_paymenttransaction_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcertificate',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
