# Generated by Django 5.2.7 on 2025-10-27 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localleague',
            name='slug',
            field=models.SlugField(default='local-league', max_length=20, unique=True, verbose_name='Unique slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localleague',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='League page subtitle'),
        ),
        migrations.AddField(
            model_name='localleague',
            name='title',
            field=models.CharField(default='local-league', max_length=100, verbose_name='Full league page title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localleague',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name to be displayed'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Full name')),
                ('short_name', models.CharField(max_length=20, verbose_name='Short name')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='matches.localleague', verbose_name='Local league to which the team belongs')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('shirt_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99, message='Shirt number cannot exceed 99'), django.core.validators.MinValueValidator(1, message='Shirt number must be at least 1')], verbose_name='Shirt number')),
                ('position', models.CharField(choices=[('POR', 'Goalkeeper'), ('DIF', 'Defender'), ('CEN', 'Midfielder'), ('ATT', 'Forward')], max_length=5, verbose_name='Playing position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matches.team', verbose_name='Team to which the player belongs')),
            ],
        ),
    ]
