# Generated by Django 5.2.7 on 2025-10-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_localleague_slug_localleague_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('POR', 'Goalkeeper'), ('DIF', 'Defender'), ('CEN', 'Midfielder'), ('ATT', 'Forward')], max_length=5, null=True, verbose_name='Playing position'),
        ),
    ]
