# Generated by Django 5.2.7 on 2025-10-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('POR', 'Portiere'), ('DIF', 'Difensore'), ('CEN', 'Centrocampista'), ('ATT', 'Attaccante')], max_length=5, null=True, verbose_name='Playing position'),
        ),
    ]
