# Generated by Django 5.2.7 on 2025-10-28 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_player_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='league',
            new_name='local_league',
        ),
    ]
