# Generated by Django 5.2.7 on 2025-10-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_rename_league_team_local_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localleague',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Local League Name'),
        ),
        migrations.AlterField(
            model_name='localleague',
            name='title',
            field=models.CharField(max_length=100, verbose_name='League page full title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Unique slug'),
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Stadium name')),
                ('address', models.CharField(max_length=100, verbose_name='Stadium address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Stadium latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Stadium longitude')),
                ('local_leagues', models.ManyToManyField(related_name='stadiums', to='matches.localleague', verbose_name='Local leagues that use this stadium')),
            ],
        ),
    ]
