# Generated by Django 5.2.7 on 2025-10-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_match_matchevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.RenameField(
            model_name='match',
            old_name='datetime',
            new_name='date',
        ),
    ]
